version: 0.2
phases:
    build:
        on-failure: ABORT
        commands:
            - echo Nothing to do in build phase.
    post_build:
        commands:
            - echo Deploying ...
            - >-
              aws s3 sync . s3://${BUCKET_NAME}/
              --exclude ".github"
              --exclude ".gitignore"
              --exclude "README.md"
              --exclude "server.js"
              --exclude "buildspec.yml"
              --exact-timestamps
              --delete
